# Install Node.js using packages crafted by NodeSource
---
- name: Ensure the system can use the HTTPS transport for APT
  stat:
    path: /usr/lib/apt/methods/https
  register: apt_https_transport

- name: Install HTTPS transport for APT
  apt:
    pkg: apt-transport-https
    state: installed
  when: not apt_https_transport.stat.exists

- name: Import the NodeSource GPG key into apt
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Check if nodejs_version is 4.x or higher
  set_fact: debian_repo_version="4.x"
  when: "{{ nodejs_version | version_compare('4.0', '>=') }}"

- name: Check if nodejs_version is 5.x or higher
  set_fact: debian_repo_version="5.x"
  when: "{{ nodejs_version | version_compare('5.0', '>=') }}"

- name: Show fact
  debug: msg="debian_repo_version = {{ debian_repo_version }}"

- name: Add NodeSource deb repository
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{ debian_repo_version }} {{ ansible_distribution_release }} main'
    state: present

- name: Add NodeSource deb-src repository
  apt_repository:
    repo: 'deb-src https://deb.nodesource.com/node_{{ debian_repo_version }} {{ ansible_distribution_release }} main'
    state: present

- name: Add NodeSource repository preferences
  template:
    src: etc/apt/preferences.d/deb_nodesource_com_node.pref.2
    dest: /etc/apt/preferences.d/deb_nodesource_com_node.pref

- name: Install Node.js
  apt:
    pkg:
      - nodejs={{ nodejs_version }}*
    state: installed
    update_cache: yes
